name: Testing secrets functionality

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "My Existing secret is ${{secrets.API_KEY}}"
