name: Testing secrets functionality

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - run: |
          echo "My Existing secret token is ${{secrets.API_KEY}}"
          echo "My Existing variable is ${{variable.API_VAR}}"
